### ISSUE TITLE
XS is not recognised as a valid country code

### ISSUE THREAD

**Issue by tomi44g** [JonaMX/js-isin-validator#3]
A special code, 'XS'. is used for international securities cleared through pan-European clearing systems like Euroclear and CEDEL. 
[See description of the structure on ison.org](https://www.isin.org/isin/)

Would it be possible to add it to the ISIN Validator?

**Comment by JonaMX** [comment]
Hey @tomi44g sorry for the late response, and thanks for pointing this issue. Working on this now

**Comment by JonaMX** [comment]
This has been solved on `v.1.0.3`
